version: '3.4'

services:
  auditexample:
    image: ${DOCKER_REGISTRY-}auditexample
    build:
      context: .
      dockerfile: src/AuditExample/Dockerfile
      
  librarydb:
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2     
    
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    
volumes:
  elasticsearch-data:
    driver: local